# This file contains values from Cookiecutter

default_context:
  project_name: "{{ cookiecutter.project_name }}"
  repo_name: "{{ cookiecutter.repo_name }}"
  package_name: "{{ cookiecutter.package_name }}"
  project_description: "{{ cookiecutter.project_description }}"
  version: "{{ cookiecutter.version }}"
  author: "{{ cookiecutter.author }}"
  scm_platform: "{{ cookiecutter.scm_platform }}"
  scm_username: "{{ cookiecutter.scm_username }}"
  email: "{{ cookiecutter.email }}"
  licence: "{{ cookiecutter.licence }}"
  minimal_python_version: {{ cookiecutter.minimal_python_version }}
  use_formatters: {{ cookiecutter.use_formatters }}
  line_length: {{ cookiecutter.line_length }}
  use_linters: {{ cookiecutter.use_linters }}
  docstring_style: "{{ cookiecutter.docstring_style }}"
  create_example_template: "{{ cookiecutter.create_example_template }}"
  create_docker: {{ cookiecutter.create_docker }}
  create_docs: {{ cookiecutter.create_docs }}
