# This file contains values from Cookiecutter

default_context:
  project_name: "{{ cookiecutter.project_name }}"
  project_description: "{{ cookiecutter.project_description }}"
  author: "{{ cookiecutter.author }}"
  licence: "{{ cookiecutter.licence }}"
  minimal_python_version: {{ cookiecutter.minimal_python_version }}
  github_name: "{{ cookiecutter.github_name }}"
  email: "{{ cookiecutter.email }}"
  version: "{{ cookiecutter.version }}"
  line_length: "{{ cookiecutter.line_length }}"
  create_example_template: "{{ cookiecutter.create_example_template }}"
  scm_base_url: "https://{{ cookiecutter.scm_platform }}.com/{{ cookiecutter.scm_username }}/{{ cookiecutter.repo_name }}"
  scm_link_url: "https://{{ cookiecutter.scm_platform }}.com/{{ cookiecutter.scm_username }}/{{ cookiecutter.repo_name }}{% if cookiecutter.scm_platform == 'gitlab' %}/-{% endif %}"
